### ISSUE TITLE
How is reference txt structured?

### ISSUE THREAD

**Issue by marcodallaba** [Oichii/DeepPulse-pytorch#2]
At line 44 of pulse_dataset_2d you initialise a reference csv.
reference = pd.read_csv(p + '.txt', sep='\t')
ref = reference.loc[:, 'waveform']
ref = np.array(ref)

How is structured that file? The numpy array does only contain the waveforms? 
How can I extract heart rate during the test phase?

Thank you

**Comment by Oichii** [comment]
It is a file containing reference PPG (waveform) and pulse values for each video frame.  In the case of the PURE dataset, the file contains additional unused values like "barGraph"  and "o2saturation" separated with tab, so the file is structured like below. 

> barGraph	beep	droppingo2Sat	o2saturation	probeError	pulseRate	searching	searchingToLong	signalStrength	waveform

> 6		False	False		97		False		83		False		False		5		48

> 6		False	False		97		False		83		False		False		5		49

> 6		False	False		97		False		83		False		False		5		49

> ...

**Comment by marcodallaba** [comment]
Thank you so much!

**Comment by Taimoor-R** [comment]
> At line 44 of pulse_dataset_2d you initialise a reference csv. reference = pd.read_csv(p + '.txt', sep='\t') ref = reference.loc[:, 'waveform'] ref = np.array(ref)
> 
> How is structured that file? The numpy array does only contain the waveforms? How can I extract heart rate during the test phase?
> 
> Thank you

Hi @marcodallaba i am wondering how you set up the PURE database as it has a json file containing frame information and pgg data but the ppg timestamps dont correspond to image timestamps.
